$dirs = @(
  "src/app/(auth)/login",
  "src/app/(dashboard)/dashboard",
  "src/app/(dashboard)/report",
  "src/app/(dashboard)/map",
  "src/app/(dashboard)/issues",
  "src/app/(dashboard)/verify",
  "src/app/(dashboard)/analytics",
  "src/app/(dashboard)/agent",
  "src/app/api/analyze-issue",
  "src/app/api/generate-resolution",
  "src/app/api/detect-duplicate",
  "src/app/api/predict-issues",
  "src/app/api/civic-agent",
  "src/app/api/voice-to-issue",
  "src/components/ui",
  "src/components/auth",
  "src/components/map",
  "src/components/issues",
  "src/components/dashboard",
  "src/components/agent",
  "src/components/layout",
  "src/components/shared",
  "src/lib/firebase",
  "src/lib/gemini",
  "src/lib/maps",
  "src/lib/stores",
  "src/lib/hooks",
  "src/lib/types",
  "src/lib/utils"
)
foreach ($d in $dirs) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

$files = @(
  "src/app/(auth)/login/page.tsx",
  "src/app/(auth)/layout.tsx",
  "src/app/(dashboard)/dashboard/page.tsx",
  "src/app/(dashboard)/report/page.tsx",
  "src/app/(dashboard)/map/page.tsx",
  "src/app/(dashboard)/issues/page.tsx",
  "src/app/(dashboard)/verify/page.tsx",
  "src/app/(dashboard)/analytics/page.tsx",
  "src/app/(dashboard)/agent/page.tsx",
  "src/app/(dashboard)/layout.tsx",
  "src/app/api/analyze-issue/route.ts",
  "src/app/api/generate-resolution/route.ts",
  "src/app/api/detect-duplicate/route.ts",
  "src/app/api/predict-issues/route.ts",
  "src/app/api/civic-agent/route.ts",
  "src/app/api/voice-to-issue/route.ts",
  "src/components/auth/LoginCard.tsx",
  "src/components/auth/AuthProvider.tsx",
  "src/components/map/CivicMap.tsx",
  "src/components/map/IssuePin.tsx",
  "src/components/map/HeatmapLayer.tsx",
  "src/components/issues/IssueCard.tsx",
  "src/components/issues/IssueForm.tsx",
  "src/components/issues/IssueDetail.tsx",
  "src/components/issues/SeverityBadge.tsx",
  "src/components/dashboard/StatsCard.tsx",
  "src/components/dashboard/ActivityFeed.tsx",
  "src/components/dashboard/ImpactChart.tsx",
  "src/components/agent/CivicAgentChat.tsx",
  "src/components/agent/AgentMessage.tsx",
  "src/components/layout/Navbar.tsx",
  "src/components/layout/Sidebar.tsx",
  "src/components/layout/PageWrapper.tsx",
  "src/components/shared/LoadingSpinner.tsx",
  "src/components/shared/AnimatedCounter.tsx",
  "src/components/shared/GlowCard.tsx",
  "src/lib/firebase/config.ts",
  "src/lib/firebase/auth.ts",
  "src/lib/firebase/firestore.ts",
  "src/lib/firebase/storage.ts",
  "src/lib/gemini/config.ts",
  "src/lib/gemini/analyzeIssue.ts",
  "src/lib/gemini/generateResolution.ts",
  "src/lib/gemini/detectDuplicate.ts",
  "src/lib/gemini/predictIssues.ts",
  "src/lib/gemini/civicAgent.ts",
  "src/lib/maps/geocoding.ts",
  "src/lib/stores/authStore.ts",
  "src/lib/stores/issueStore.ts",
  "src/lib/stores/uiStore.ts",
  "src/lib/hooks/useAuth.ts",
  "src/lib/hooks/useIssues.ts",
  "src/lib/hooks/useGeolocation.ts",
  "src/lib/hooks/useVoice.ts",
  "src/lib/types/index.ts",
  "src/lib/utils/formatters.ts",
  "src/lib/utils/validators.ts"
)
foreach ($f in $files) { 
  New-Item -ItemType File -Force -Path $f | Out-Null 
  if ($f.EndsWith("page.tsx") -or $f.EndsWith("layout.tsx")) {
    Set-Content -Path $f -Value "export default function Component() { return null; }"
  } elseif ($f.EndsWith(".tsx") -or $f.EndsWith(".ts")) {
    Set-Content -Path $f -Value "export {};"
  }
}
